README.md: guessinggame.sh

	echo "This code contains the following number of lines:" >> README.md
	wc -l guessinggame.sh | egrep -o "[0-9]+" >> README.md
	echo "" >> README.md
	echo "'Lines of code', in this case, also includes non-commentary lines." >> README.md


