README.md: guessinggame.sh

	#The Unix Workbench: Peer Graded Assignment
	## By Jessica Singer



	echo "This code contains the following number of lines:" > README.md
	wc -l guessinggame.sh | egrep -o "[0-9]+" >> README.md
	echo "" >> readme.txt
	echo "'Lines of code', in this case, also includes non-commentary lines." >> readme.txt
